### ISSUE TITLE
TS43: Client checking, user can't input company name of client

### ISSUE THREAD

**Issue by Lex-Castro** [vasavah/vsv-fli-pass-uat#10]
**Describe the bug**
The fields where company name of customer/client of the company applying for accreditation cannot be clicked/edited

**To Reproduce**
1. Go to 'Credentials'
2. Click on the blank fields under 'Customer/Client Company Name''
3. See error

**Expected behavior**
User should be able to place a caret/text cursor in the field, edit, add, remove text

**Screenshots**
![image](https://user-images.githubusercontent.com/52643156/60790783-dc041e80-a194-11e9-880c-99de400f1164.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Microsoft Edge]
 - Version [41.16299.15.0]

**Comment by HannahCastro** [comment]
This is for closing.
