### ISSUE TITLE
TS99: Remarks field in CMAP Assessment tab to be transferred to Vendor Information tab

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-pass-uat#100]
**Describe the bug**
As the other tabs have been hidden due to access limitations for canvassers and end-users, Remarks field that in CMAP Assessment tab cannot be used by those users to input their comments regarding the vendor.

**To Reproduce**
1. Go to 'Vendor List'
2. Click on 'View' for a certain vendor to comment on
3. See error

**Expected behavior**
Remarks field will be transferred to Vendor Information tab so that canvassers and end-users will be able to input their remarks. This is CPCAD and OTPs requirement so that they can indicate interview status or whatever comments are needed.

**Screenshots**
![image](https://user-images.githubusercontent.com/51902789/64084426-0b32a880-cd5e-11e9-9a8a-8a6f9f51790c.png)
![image](https://user-images.githubusercontent.com/51902789/64084442-22719600-cd5e-11e9-8400-48575258951c.png)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Comment by Lex-Castro** [comment]
This is now resolved.

![image](https://user-images.githubusercontent.com/52643156/79711822-91a2f700-82fb-11ea-95cc-219667fabf47.png)
