### ISSUE TITLE
Password generation for New Vendors

### ISSUE THREAD

**Issue by Reyzelle** [vasavah/vsv-fli-pass-uat#102]
**Describe the bug**
Currently set as (qwerty), change to random password generation. Password provided in the email (new accounts, password reset) is not secure enough.

**Expected behavior**
System should generate random passwords.

**Screenshots**
![image](https://user-images.githubusercontent.com/64526823/80583103-5cf11700-8a42-11ea-8958-99b8fb5abc74.png)

**Comment by HannahCastro** [comment]
This issue is resolved. @Reyzelle please close ticket.
