### ISSUE TITLE
Update link provided in email to new website for PASS

### ISSUE THREAD

**Issue by Reyzelle** [vasavah/vsv-fli-pass-uat#103]
**Describe the bug**
Link in the email is not updated. When clicked, website is not loaded.

**Expected behavior**
Vendor to update link to final URL.

**Comment by HannahCastro** [comment]
Please refer to the screenshot below.
![image](https://user-images.githubusercontent.com/51902789/80956175-41678100-8e33-11ea-904e-889753c8fa78.png)

This is applicable for the link found in the email invite and in the document uploads.

**Comment by HannahCastro** [comment]
This issue is resolved. @Reyzelle please close ticket.
