### ISSUE TITLE
TS25: Email Address Incorrect Syntax Notification

### ISSUE THREAD

**Issue by Lex-Castro** [vasavah/vsv-fli-pass-uat#11]
**Describe the bug**
When invitations are sent to email addresses with wrong syntax, there's no notice/notification/prompt - there should be

**To Reproduce**
1. Go to 'Invite New Supplier'
2. Fill out required fields
3. Fill out incorrect email address (incorrect syntax)

**Expected behavior**
Invite will not proceed and the user is notified that email syntax is invalid

**Screenshots**
![image](https://user-images.githubusercontent.com/52643156/60792531-731ea580-a198-11e9-9689-c9a5a090d627.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Microsoft Edge]
 - Version [41.16299.15.0]

**Comment by HannahCastro** [comment]
Email address field accepts xxxxx@xxxxx only. This is related to TS1: Email syntax is incomplete (account management and vendor invitation) - submitted July 17, 2019. **Issue hasn't been resolved**.

**Comment by HannahCastro** [comment]
As of August 13, system prompts error if email address doesn't include ".com" or equivalent.
![image](https://user-images.githubusercontent.com/51902789/62912539-3b200900-bdbb-11e9-9b01-c6901a4ec09d.png)
![image](https://user-images.githubusercontent.com/51902789/62912463-eaa8ab80-bdba-11e9-984a-7970dbfe9182.png)

**This is now for closing.**
