### ISSUE TITLE
For searching via STATUS, have a dropdown for the status types

### ISSUE THREAD

**Issue by Reyzelle** [vasavah/vsv-fli-pass-uat#116]
**Describe the bug**
Free text field for searching a vendor via status (in the Dashboard > All Vendors list)

**Expected behavior**
Instead of a free text field for searching a vendor via status (in the Dashboard > All Vendors list), this should be a dropdown field instead of the different vendor status.

**Comment by HannahCastro** [comment]
This issue is resolved. @matthewroman for your assistance in closing ticket.
![image](https://user-images.githubusercontent.com/51902789/83609087-58270200-a5b0-11ea-9751-c05398e11a65.png)
![image](https://user-images.githubusercontent.com/51902789/83608732-e353c800-a5af-11ea-80a8-c057e24ea754.png)
