### ISSUE TITLE
For rejected accreditation

### ISSUE THREAD

**Issue by Reyzelle** [vasavah/vsv-fli-pass-uat#117]
**Describe the bug**
Make remarks/reason for rejection a required field and note who made the rejection.

**Expected behavior**
System should require the Remarks/Reason field when a vendor application is rejected. Name of rejector should also be included.

**Comment by HannahCastro** [comment]
This issue is resolved. @matthewroman for your assistance in closing ticket.
![image](https://user-images.githubusercontent.com/51902789/83609313-b3f18b00-a5b0-11ea-9edd-1d4557dbbae6.png)
![image](https://user-images.githubusercontent.com/51902789/83609278-a2a87e80-a5b0-11ea-9f59-3444a36080b6.png)
