### ISSUE TITLE
For approved accreditation with failing marks

### ISSUE THREAD

**Issue by Reyzelle** [vasavah/vsv-fli-pass-uat#118]
**Describe the bug**
Make remarks/reason for approval a required field and note who made the approval

**Expected behavior**
If a vendor application with "Fail" grade is accredited, system should require Remarks/Reason field. Name of acccreditor should also be included.

**Comment by HannahCastro** [comment]
This issue is resolved. @matthewroman for your assistance in closing ticket.
![image](https://user-images.githubusercontent.com/51902789/83610330-dcc65000-a5b1-11ea-8798-49c3fe13200e.png)
