### ISSUE TITLE
Report output would be a file they can upload to other systems

### ISSUE THREAD

**Issue by Reyzelle** [vasavah/vsv-fli-pass-uat#119]
**Describe the bug**
Report output would be a file they can upload to other systems e.g. vendor list with EWB numbers

**Expected behavior**
Reports generated will be an excel or csv file that can be used to upload to other systems.

**Comment by VCI-Jojo** [comment]
@HannahCastro Tagging this as invalid as we will not be creating a new report for this but just adding the EWB number to an existing report. Kindly closed this ticket and create a new ticket for that and attached the revised report format with EWB number. Thank you.

**Comment by HannahCastro** [comment]
@VCI-Jojo Noted, we'll close this ticket. The report we already endorsed already contains data on EastWest Bank details. Please see sheet "Vendor Database (For All)" in the report template previously endorsed.

@Reyzelle please close this ticket.
