### ISSUE TITLE
TS19: System allowed user to proceed inviting existing company

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-pass-uat#12]
**Describe the bug**
If Company Name encoded exists, but other details don't exist, system will prompt that vendor has been invited or exists and will not allow user to proceed with the invite. However, if the email address included exists, system will ask user if it will invite vendor again, not taking into consideration if vendor is accredited or validity of rejection/suspension is still effective.

**To Reproduce**
1. Go to 'Invite New Supplier'
2. Encode Company Name (existing - UNI-POWER HEAVY LIFT CORP.) and other details (not existing - hannahcastro7@gmail.com)
3. Click on 'Invite New Supplier'
vs.
1. Go to 'Invite New Supplier'
2. Encode Company Name (existing - UNI-POWER HEAVY LIFT CORP.) and other details (existing - hannahcastro7@yahoo.com)
3. Click on 'Invite New Supplier'

**Expected behavior**
If system checked that Company Name is already existing, it should prompt the user that vendor already exists and will not allow the user to proceed, regardless of the other details encoded.

**Screenshots**
![image](https://user-images.githubusercontent.com/51902789/60792638-a5300780-a198-11e9-8ca4-5a227dcf5a86.png)
![image](https://user-images.githubusercontent.com/51902789/60792808-ede7c080-a198-11e9-87df-e3df89444e1c.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Comment by Lex-Castro** [comment]
System no longer allows inviting existing company (which is good)

however, this also prevents user to re-invite vendors who were invited (but did not respond hence no actual account yet)

I think we should define "existing company" as one who at least submitted application. While re-inviting "invited already" companies will just ask for a confirmation, but may still proceed.

![image](https://user-images.githubusercontent.com/52643156/61445131-5bf16c00-a97f-11e9-9ac9-cc7f451b12ee.png)

**Comment by Lex-Castro** [comment]
Please see development on UAT for this Test Case.

Results regarding sending invitations are as expected except for the following:

- Sending invitations to vendors who have already been invited but without response. System should ask confirmation but actual result proceeds without question

- System allows the plus (+) symbol at the beginning (this is okay). System should also allow the use of the symbols: hyphens (-), spaces, parentheses regardless of syntax when inserting contact no. This is so user will not have to "adjust" to any format if he/she is just "copy-pasting" a mobile no. from websites and the like

For more details, kindly refer to images below and the excel file attached

[INVITING VENDORS (TEST CASES).xlsx](https://github.com/vasavah/vsv-fli-pass-uat/files/3507897/INVITING.VENDORS.TEST.CASES.xlsx)


![image](https://user-images.githubusercontent.com/52643156/63139667-b0851700-c011-11e9-86a2-372014d1c0a3.png)

![image](https://user-images.githubusercontent.com/52643156/63140178-92201b00-c013-11e9-9c5c-50f919dc2dff.png)

**Comment by Lex-Castro** [comment]
This issue remains unresolved. System still treats invited vendors as "existing" automatically.

Contact Mobile Number still does not allow entry of non-numeric data, and even if it does allow user to enter symbols i.e. +, -, etc. submission is blocked by system.

**Comment by Lex-Castro** [comment]
The system now allows the use of symbols for the contact mobile number field.

however the system allows sending invitations to email address that was already invited.

Expected result: When sending an invite to the same email address (different company), system will ask confirmation

Actual result: System proceeds and sends invite without question.

The image below shows invited vendors with the same email addresses - system sends invite without prompt.

**Comment by HannahCastro** [comment]
This issue is now resolved.
![image](https://user-images.githubusercontent.com/51902789/83592916-0a999d80-a58e-11ea-8751-7300b88328ec.png)
