### ISSUE TITLE
Email address used in vendor invitation was not defaulted to the contact details in the application form

### ISSUE THREAD

**Issue by Reyzelle** [vasavah/vsv-fli-pass-uat#121]
**Describe the bug**
Email address used in vendor invitation was not defaulted to the contact details in the application form

**Expected behavior**
Email address used in the vendor invitation should be defaulted in the application form. Vendor can edit it if necessary.

**Comment by HannahCastro** [comment]
This issue is resolved. @matthewroman for your assistance in closing ticket.
![image](https://user-images.githubusercontent.com/51902789/83615664-704f4f00-a5b9-11ea-9344-8d4fc29f8ee4.png)
![image](https://user-images.githubusercontent.com/51902789/83615703-80ffc500-a5b9-11ea-8ae1-ef5820fe439d.png)
