### ISSUE TITLE
Dates should be included in the filtering

### ISSUE THREAD

**Issue by Reyzelle** [vasavah/vsv-fli-pass-uat#123]
**Is your feature request related to a problem? Please describe.**
Dates should be included in the filtering (ex. Expired Vendors)

**Describe the solution you'd like**
When filtering, dates should be included (year, month).

**Comment by HannahCastro** [comment]
@matthewroman for your assistance in closing.
![image](https://user-images.githubusercontent.com/51902789/83611177-354a1d00-a5b3-11ea-8026-a165037f3c23.png)
