### ISSUE TITLE
TS15: My Profile and Sign Out are not working

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-pass-uat#124]
**Describe the bug**
Some users have reported that My Profile and Sign Out are not working. When they are clicked, nothing happens.

**To Reproduce**
1. Go to the menu found at the upper right corner of the system.
2. Click on either 'My Profile' or 'Sign Out'
3. See error

**Expected behavior**
When My Profile is clicked, user should be redirected to their Profile page. When Sign Out is clicked, user will be logged out of the system

**Desktop (please complete the following information):**
User 1:
-  OS: Windows 10
 - Browser: Google Chrome
 - Version 81.0.4044.129
User 2: 
-  OS: Windows 10 Pro
 - Browser: Google Chrome
 - Version 81.0.4044.129

**Comment by Lex-Castro** [comment]
I discovered that my account's profile is inaccessible as well. The system just refreshes my current page.

Note:

My account is an accreditor reviewer (user: pocholo.castro) and my sign out is working fine.
My account has been disabled and activated recently (for testing purposes)
account user: admin has a working profile and sign out
