### ISSUE TITLE
Add Product Tags field

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-pass-uat#145]
**Is your feature request related to a problem? Please describe.**
To provide more details on what products a vendor carry, there should be a separate field to indicate those items.

**Describe the solution you'd like**
Add Product Tags field in Vendor Information. This will be a free text field. SAT will be the ones to encode in this field.
This should also be a filter for searching. When searching for a vendor using product tags, any keyword indicated in that field should be acknowledged by the system.

**Comment by JenBragat** [comment]
![product tags](https://user-images.githubusercontent.com/66242268/83612936-a985c000-a5b5-11ea-82ca-a611f100e16f.JPG)
