### ISSUE TITLE
TS39: Buggy Graphs in 'Financial Capacity'

### ISSUE THREAD

**Issue by Lex-Castro** [vasavah/vsv-fli-pass-uat#15]
**Describe the bug**
The information reflected in graphs are misrepresented or outright incorrect.

**To Reproduce**
1. Go to 'Financial Capacity' when viewing vendor
2. See error

**Expected behavior**
1. Doughnut Graph: should represent data accurately (bug: inventories and current assets are interchanged)
2. Bar Graph: Labels should show each test and their result (bug: all labels are "acid test")
3. Colum Graph: should show Net Profit/loss (sales less expenses)

**Screenshots**
![image](https://user-images.githubusercontent.com/52643156/60797855-ac5c1300-a1a2-11e9-85dd-69483f9aade3.png)
![image](https://user-images.githubusercontent.com/52643156/60797882-bb42c580-a1a2-11e9-9549-7d656d34304b.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Microsoft Edge]
 - Version [41.16299.15.0]

**Comment by Lex-Castro** [comment]
There is mismatch of information between the graph and its equivalent comments (see image for details)

![image](https://user-images.githubusercontent.com/52643156/61345481-ed7db280-a887-11e9-88b1-52b375df7055.png)




Also (see image)
![image](https://user-images.githubusercontent.com/52643156/61345826-3d10ae00-a889-11e9-88a7-954c0dcfc183.png)


Also can we fix alignment of graphs and comments (see image)
![image](https://user-images.githubusercontent.com/52643156/61346372-09368800-a88b-11e9-9458-5a1d09fde879.png)

**Comment by zetaleona** [comment]
Should match information.

![pasted image 0](https://user-images.githubusercontent.com/50394125/62052945-2aaf5080-b249-11e9-84e5-3eb096677dd4.png)

**Comment by Lex-Castro** [comment]
Alignment, commas between thousands, groupings are okay. Persisting and new issues are as follows:

**(a) mismatching comments**

The actual assessment is "3" (see image below)
and the comment (in red box) associated is:

 _"Liquid assets are certainly insufficient to meet current liabilities. Liquidity can be described as critical. Unlikely to meet short term financial obligations."_

![image](https://user-images.githubusercontent.com/52643156/63077562-46199b80-bf6b-11e9-8b1d-96fdcd6f5820.png)

Correct comment for a "3" should be:

![image](https://user-images.githubusercontent.com/52643156/63077659-a3ade800-bf6b-11e9-8446-3db2e00f53c5.png)

This should apply to all tests.  the actual assessment score should mirror the comments
![image](https://user-images.githubusercontent.com/52643156/63077844-377fb400-bf6c-11e9-83e0-5db1b957da55.png)

**(b) visible comment matrix**
The comments matrix should not be visible to users, only the appropriate comments should be shown.

**(c) Y-axis data for doughnut graph**
There should be no y-axis data for the graph
![image](https://user-images.githubusercontent.com/52643156/63077993-abba5780-bf6c-11e9-8cfa-5c6ef09badbc.png)

**(d) feature to hide all data in netprofit(loss) graph**
This is not a needed feature; it doesn't hide specific data, it hides all data.
![image](https://user-images.githubusercontent.com/52643156/63078613-9f36fe80-bf6e-11e9-9928-48d83e767e11.png)

**Comment by Lex-Castro** [comment]
Found a typo:

![image](https://user-images.githubusercontent.com/52643156/63757197-3fd0db00-c8ec-11e9-98de-67524f244745.png)

Since these "comments" change depending on the average data, there may be other typos I cannot check.

**Comment by Lex-Castro** [comment]
Typo wasn't completely removed, semi colon (;) should be removed as well

**Comment by Lex-Castro** [comment]
Typo is now gone.
