### ISSUE TITLE
TS37: Notification feature isn't functioning

### ISSUE THREAD

**Issue by Lex-Castro** [vasavah/vsv-fli-pass-uat#16]
**Describe the bug**
The notification "center" next to your name on top of each page shows no change, update, and whatsoever. it's always free from content

**To Reproduce**
1. Click on 'notification' button on top right of the page, it's a "new file" icon (paper)
2. See error

**Expected behavior**
Notifications should pop up when new vendors apply for accreditation, submit requirements, etc. 

**Screenshots**
![image](https://user-images.githubusercontent.com/52643156/60855904-fe9b4380-a237-11e9-8061-ad3cae209d52.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Microsoft Edge]
 - Version [41.16299.15.0]

**Comment by HannahCastro** [comment]
Notification is now working for SAT Reviewer. This is for closing.

**Comment by HannahCastro** [comment]
Canvassers do not receive notifications for vendor status.
![image](https://user-images.githubusercontent.com/51902789/61532873-d55f8c00-aa5d-11e9-9b1b-8eda073ec41b.png)

**Comment by HannahCastro** [comment]
This is for closing.
