### ISSUE TITLE
TS19: Tickbox and notification for updating user of status are not working

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-pass-uat#19]
**Describe the bug**
Tickbox for "Update me status of supplier" is not clickable. It already has a default check mark. This should also be "Update me of status of the supplier/contractor". Also, user wasn't notified if a vendor was accredited or rejected.

**To Reproduce**
1. Go to 'Invite New Supplier'
2. Click on tickbox for 'Update me status of supplier'.
3. See error
4. SAT processes application
5. See error

**Expected behavior**
Tickbox should be clickable so default check mark should be removable. Then, once vendor is processed (accredited, rejected, etc.), user who sent an invite should be notified of the status of the vendor. 

**Screenshots**
![image](https://user-images.githubusercontent.com/51902789/60874117-18ee1500-a26a-11e9-8a4b-17aa034fdf08.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Comment by matthewroman** [comment]
Comments for devs:

1. Check box should not be disabled (it should be able to toggle)
2. If checked, notifications should be received.  If not checked, no notifications should be received.

**Comment by HannahCastro** [comment]
Canvassers only receive notification if a vendor they invited is accredited or rejected.
![image](https://user-images.githubusercontent.com/51902789/61604013-7a52b280-ac72-11e9-9dcd-db9517b6bcc6.png)

We will now close the ticket.
