### ISSUE TITLE
TS36: System logs out account once application is submitted and enables editing of application

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-pass-uat#22]
**Describe the bug**
Once a supplier submits their application form, system automatically logs out of the system. Then, when supplier opens their account to check on their status, they are redirected to their filled up application form and are able to edit their details. If an application was fully processed (accredited, rejected), application goes back to For Review and Approval with the updated application form details.

**To Reproduce**
1. As vendor J Co., open account (johanna.castro3 qwerty@2)
2. Fill up application form and submit once completed. System automatically logs out the application form
3. As vendor J Co., to check status of application, open account (johanna.castro3 qwerty@2)

**Expected behavior**
Once vendor has successfully submitted their application, application will be locked and they should be able to see their locked application with status as For Review and Approval. If they go to their account again to check their status, the system should load the locked application with the updated status.

**Screenshots**
![image](https://user-images.githubusercontent.com/51902789/60937568-78e4ca00-a303-11e9-9fc9-00adec56036c.png)
![image](https://user-images.githubusercontent.com/51902789/60938104-476cfe00-a305-11e9-88f7-c8aeb84326fb.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Comment by matthewroman** [comment]
Feature enhancement and pushed to cycle 2

**Comment by Lex-Castro** [comment]
Already with ticket (previously  mentioned and thought to be without ticket)
This issue is not fixed yet.

**Comment by HannahCastro** [comment]
As of July 19, 2019, issue hasn't been fixed yet.
1. System still logs out once vendor has submitted submitting their application form.
2. Once vendor has undergone the accreditation process and accesses their account, they are still able to edit the account. So, their current status (either Accredited or Rejected) changes back to Pending Requirements (if not yet submitted) or For Review and Approval (if done submitting).

![image](https://user-images.githubusercontent.com/51902789/61501042-16c14e80-aa00-11e9-929f-a036a1d8c4e4.png)
![image](https://user-images.githubusercontent.com/51902789/61501065-3c4e5800-aa00-11e9-8acb-0aa660b5cb99.png)
![image](https://user-images.githubusercontent.com/51902789/61501087-58ea9000-aa00-11e9-8b5e-24aa95063da8.png)
![image](https://user-images.githubusercontent.com/51902789/61501104-74ee3180-aa00-11e9-81d6-e1e82a1a2d0c.png)
