### ISSUE TITLE
Consolidated adjustments and errors

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-pass-uat#24]
**Describe the bug**
As discussed with Joe yesterday, we are to submit a consolidated list of adjustments and errors found in the system. These issues are related to typographical errors, editing of fields and field types, color changes, functionalities not working, and others. The attached file describes each issue.
[PASS CYCLE 1 ADJUSTMENTS.docx](https://github.com/vasavah/vsv-fli-pass-uat/files/3376657/PASS.CYCLE.1.ADJUSTMENTS.docx)

**To Reproduce**
Please see attached file

**Expected behavior**
Please see attached file for expected behavior/change for each issue.

**Screenshots**
Please see attached file

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Comment by matthewroman** [comment]
This has been converted into multiple tickets.
