### ISSUE TITLE
TS106 Notification for the newly submitted application forms

### ISSUE THREAD

**Issue by zetaleona** [vasavah/vsv-fli-pass-uat#28]
•	SAT Reviewer didn’t receive a notification for the newly submitted application forms for processing.

**Comment by HannahCastro** [comment]
This has been reported under TS37: Notification feature isn't functioning

**Comment by HannahCastro** [comment]
SAT Reviewer now receives notification. In place of being reminded to process an application that was not processed after 1 day, the system doesn't remove the notification if not processed. This can now be closed.
