### ISSUE TITLE
TS105 Filtering and sorting

### ISSUE THREAD

**Issue by zetaleona** [vasavah/vsv-fli-pass-uat#29]
•	Filtering should be latest to oldest. Able to sort alphabetically.

![25](https://user-images.githubusercontent.com/50394125/61118311-0d4d5900-a4cb-11e9-90d0-4642268a4632.png)

**Comment by HannahCastro** [comment]
Sorting alphabetically is not yet available. This is not yet resolved.

**Comment by HannahCastro** [comment]
As of August 13, ticket is not yet resolved. We are now able to sort alphabetically and chronologically.
![image](https://user-images.githubusercontent.com/51902789/62923587-a6c89d00-bde0-11e9-89cf-784753656797.png)

However, data is still not listed from latest to oldest. We are not sure if data already encoded in the system bypassed the filtering system or if it follows a different protocol compared to ones we are adding each cycle of testing. In this scenario, AN Company's status was changed from Ongoing Assessment to For Review and Approval, so the company should be at the top of the list (with tagging "New").
![image](https://user-images.githubusercontent.com/51902789/62923728-f73ffa80-bde0-11e9-8876-b9d2e492fc13.png)

**Comment by Lex-Castro** [comment]
This appears to be working as intended. This ticket is for closing.

**Comment by HannahCastro** [comment]
@zetaleona please close this ticket as this issue is resolved (based on the chronological series of the vendor code).
![image](https://user-images.githubusercontent.com/51902789/74729651-bdfcb180-527f-11ea-89ea-f04d94936a5a.png)

**Comment by zetaleona** [comment]
> @zetaleona please close this ticket as this issue is resolved (based on the chronological series of the vendor code).
> ![image](https://user-images.githubusercontent.com/51902789/74729651-bdfcb180-527f-11ea-89ea-f04d94936a5a.png)

Noted.
