### ISSUE TITLE
TS3: Unintentional user/role access change

### ISSUE THREAD

**Issue by Lex-Castro** [vasavah/vsv-fli-pass-uat#3]
**Describe the bug**
My account was created as an approver for PASS. I "invited" a supplier but entered my email address as the recipient. PASS did send an invite to my email address however it changed my account from **approver** to **supplier/vendor** - I don't see approver access but I can't see supplieras well.

**To Reproduce**
1. Go to 'Invite New Supplier...'
2. Enter your own email address
3. Go to your email, click link from invite

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/52643156/60780831-95053180-a172-11e9-893f-0a10581e84d6.png)
![image](https://user-images.githubusercontent.com/52643156/60780895-d4338280-a172-11e9-96c8-83109c3e3509.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Microsoft Edge]
 - Version [41.16299.15.0]

**Comment by HannahCastro** [comment]
Done. System prompts that email is not available.

![image](https://user-images.githubusercontent.com/51902789/61339537-c1a30280-a870-11e9-8905-eadd49748515.png)
