### ISSUE TITLE
TS100 There should be list of vendors 

### ISSUE THREAD

**Issue by zetaleona** [vasavah/vsv-fli-pass-uat#33]
•	There should be a list where all vendors, regardless of status, are found.

![26](https://user-images.githubusercontent.com/50394125/61117236-a62ea500-a4c8-11e9-97d2-751352a258fa.png)

**Comment by HannahCastro** [comment]
Dashboard box for listing of all vendors has now been added but there is no listing under "Vendor List". Also, this should be called "All Vendors", instead.
![image](https://user-images.githubusercontent.com/51902789/62921948-b645e700-bddc-11e9-8123-618476c1bb20.png)
![image](https://user-images.githubusercontent.com/51902789/62922167-5bf95600-bddd-11e9-975a-1b4fd5d75350.png)

**Comment by HannahCastro** [comment]
As of February 18, this issue is not yet resolved.

**Comment by HannahCastro** [comment]
List of all vendors is still just in the dashboard and not in the menu.
![image](https://user-images.githubusercontent.com/51902789/81625826-95bec200-942c-11ea-9472-32bca79c5bf1.png)
![image](https://user-images.githubusercontent.com/51902789/81625846-a111ed80-942c-11ea-8775-55275035b645.png)

**Comment by HannahCastro** [comment]
@zetaleona All Vendors list has been included in the Vendors List. Ticket is for closing.
![image](https://user-images.githubusercontent.com/51902789/83589992-64e33000-a587-11ea-93bb-1d15268f342d.png)
![image](https://user-images.githubusercontent.com/51902789/83590033-77f60000-a587-11ea-8ba6-692fcdbae127.png)
