### ISSUE TITLE
TS107 System allowed SAT Approver to process accreditation without SAT Reviewer

### ISSUE THREAD

**Issue by zetaleona** [vasavah/vsv-fli-pass-uat#34]
The system allowed SAT Approver to process accreditation without SAT Reviewer processing the accreditation.

**Comment by HannahCastro** [comment]
When we tested, SAT Approver was able to process the application directly. Ideally, applications should be processed by the Reviewer first.

Please give input if we should retain the functionality that the Approver can process directly without having to go thru the Reviewer first.

**Comment by matthewroman** [comment]
Hi Hanna, as approvers are higher in the hierarchical chain, and following the principle of least privilege, I suggest that approvers should retain this privilege unless there is a check and balance requirement that must be satisfied.

If it is the former, I suggest that we close the ticket.

**Comment by HannahCastro** [comment]
Upon checking with SAT, we can keep this feature that SAT Approver 1 can process an application directly, without SAT Reviewer processing the application. They just want assurance that there will be no double processing. If SAT Reviewer processes an application and forwards it to SAT Approver 1, SAT Approver 1 will be notified.

**Comment by matthewroman** [comment]
Yes that is correct.  Closing ticket.
