### ISSUE TITLE
TS108  Change the function of percentage of invited vendors that are complying

### ISSUE THREAD

**Issue by zetaleona** [vasavah/vsv-fli-pass-uat#35]
o	Change: Function: percentage of invited vendors that are complying
o	Add: Breakdown:
	No. of invited vendors
	No. of vendors that submitted the application

![27](https://user-images.githubusercontent.com/50394125/61118948-679ae980-a4cc-11e9-8bf2-f000f5316bd1.png)

**Comment by HannahCastro** [comment]
"Completion" has been renamed to "Vendor Application Completion" and percentage has been updated to remove the decimals.
Addition of breakdown has not been added yet.

![image](https://user-images.githubusercontent.com/51902789/61431276-7e738d00-a95f-11e9-962f-1a6e16268d87.png)

**Comment by HannahCastro** [comment]
As of August 14, breakdown for Vendor Application Completion has been added.
![image](https://user-images.githubusercontent.com/51902789/62917754-171af280-bdd0-11e9-9484-7a21c83e5e7f.png)

**This ticket can now be closed.**
