### ISSUE TITLE
TS111 tagging in suppliers should last for one week

### ISSUE THREAD

**Issue by zetaleona** [vasavah/vsv-fli-pass-uat#38]
•  “NEW” Tagging in suppliers should last for one (1) week.

![26](https://user-images.githubusercontent.com/50394125/61121130-12ada200-a4d1-11e9-8d54-2c81db9d335d.png)

**Comment by matthewroman** [comment]
Hi Hannah, please elaborate.

**Comment by HannahCastro** [comment]
We noticed the "New" tags but are not sure how long these tags last. These are related to changes in status of a vendor (new application, newly accredited, newly rejected, etc.). As directed by SAT, if possible, after 1 week, the "New" tag should be removed.

**Comment by matthewroman** [comment]
Understood!  We will revise the algorithm.

**Comment by HannahCastro** [comment]
For vendors that we are processing, "New" tag is gone after 1 day.

![image](https://user-images.githubusercontent.com/51902789/61519251-029c4200-aa3e-11e9-9a47-4cef0a595488.png)

**Comment by HannahCastro** [comment]
Using "Invited Vendors" category as basis, "New" tag is only retained for one week.
![image](https://user-images.githubusercontent.com/51902789/63070583-5a9b6b00-bf4e-11e9-92a1-ec8224b2bfec.png)

**This ticket can now be closed.**
