### ISSUE TITLE
TS19: checkbox not functional

### ISSUE THREAD

**Issue by Lex-Castro** [vasavah/vsv-fli-pass-uat#4]
**Describe the bug**
Checkbox cannot be unchecked

**To Reproduce**
1. Go to 'Invite New Supplier'
2. Click on Checkbox 'Update me status of supploer.'
3. See error

**Expected behavior**
The checkbox will be checked/unchecked and will function as an on/off trigger to notifying the user

**Screenshots**
![image](https://user-images.githubusercontent.com/52643156/60781567-8ff5b180-a175-11e9-819e-2693f532d551.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Microsoft Edge]
 - Version [41.16299.15.0]

**Comment by HannahCastro** [comment]
Done. Checkbox is now clickable. Wording has also been edited. This can now be closed as "TS19: Tickbox and notification for updating user of status are not working" includes testing for the notification feature.

![image](https://user-images.githubusercontent.com/51902789/61349892-51a87280-a898-11e9-8728-a6435651b126.png)
![image](https://user-images.githubusercontent.com/51902789/61349902-58cf8080-a898-11e9-861d-f6b7c1b4caa8.png)
