### ISSUE TITLE
TS114 Retain audit trail details

### ISSUE THREAD

**Issue by zetaleona** [vasavah/vsv-fli-pass-uat#41]
• If a user is deleted, will it delete all data for the audit trail? This should be “Deactivate” instead so that data will be retained.

**Comment by HannahCastro** [comment]
As of July 18, 2019, deactivation is still not available in the system.

**Comment by HannahCastro** [comment]
As of August 13, Deactivate button is now available in Manage Users module. Audit trail for deactivated account is also retained.
![image](https://user-images.githubusercontent.com/51902789/62910874-d8c40a00-bdb4-11e9-979e-f96e937ecc9b.png)
![image](https://user-images.githubusercontent.com/51902789/62910897-ea0d1680-bdb4-11e9-87db-fcb8dff4bcb0.png)
![image](https://user-images.githubusercontent.com/51902789/62911041-6f90c680-bdb5-11e9-8c8e-458f6187a71f.png)

**This ticket can now be closed.**
