### ISSUE TITLE
TS115 Adding, Editing, Delete, And Deactivate Data

### ISSUE THREAD

**Issue by zetaleona** [vasavah/vsv-fli-pass-uat#42]
•	Delete function should be present but is not the recommended course of action. This will only be used for double and incorrect entries.
•	Deactivation should be the primary course of action to retain data history.
•	For dropdown values, as discussed, this will be coursed thru Vasavah
•	For templates (email messages, certificate, evaluation form, etc.), 
o	SLA should be set so that Vasavah will resolve within the set SLA.

**Comment by matthewroman** [comment]
Deactivation is sorted in a different ticket.

For everything else, we recommend that these be Vasavah actions as they are impact data integrity.  This should be part of the maintenance agreement.  SLA will be part of the agreement.

Propose we close this ticket and handle this offline.

**Comment by HannahCastro** [comment]
Noted. Let's have a separate ticket for deactivation. We prefer deactivation as this keeps the data in the system.

**Comment by matthewroman** [comment]
Deactivation is covered in ticket 41

**Comment by HannahCastro** [comment]
Noted. We can close the ticket.

**Comment by HannahCastro** [comment]
@zetaleona please close this ticket so that it won't appear as a ticket we will have to test.

**Comment by zetaleona** [comment]
> @zetaleona please close this ticket so that it won't appear as a ticket we will have to test.

Noted.
