### ISSUE TITLE
TS15: Non-admin User can change his/her account details

### ISSUE THREAD

**Issue by Lex-Castro** [vasavah/vsv-fli-pass-uat#43]
**Describe the bug**
User was able to change the following:
-photo
-name (first name, middle name, last name)
-contact number
-email address
-designation
-department
Audit trail was updated.

**To Reproduce**
1. Go to 'Profile'
2. Change account details stated above
3. See error

**Expected behavior**
Non-admin user should only be able to edit his/her contact no.

**Screenshots**
![image](https://user-images.githubusercontent.com/52643156/61341989-3a0ec100-a87b-11e9-908e-93e2a25ffe42.png)

**Comment by HannahCastro** [comment]
Please note that a user can only edit their **photo**, **contact number**, and **password** only.

All else, if there is a need to edit the data, user will have to contact admin to change the details.

**Comment by HannahCastro** [comment]
User is now only able to change their password, contact number and photo, but changes made were not noted in the audit trail. **Changes in account should also be noted in the audit trail. This has been raised in ticket #73 Not all changes in an account are noted in the activity/audit trail so this ticket can now be closed.**
![image](https://user-images.githubusercontent.com/51902789/62753349-de141280-ba9d-11e9-86a9-16be9905315e.png)
![image](https://user-images.githubusercontent.com/51902789/62753378-0734a300-ba9e-11e9-984b-dd4d60a1eb86.png)
