### ISSUE TITLE
TS45: CMAP assessment won't proceed

### ISSUE THREAD

**Issue by Lex-Castro** [vasavah/vsv-fli-pass-uat#45]
**Describe the bug**
CMAP assessment won't show despite 

**To Reproduce**
1. As reviewer, go to supplier for accreditation (review)
2. Do standard process (checking and all)
3. Go to CMAP assessment

**Expected behavior**
After updating credentials, CMAP should allow reviewer to continue

**Screenshots**
![image](https://user-images.githubusercontent.com/52643156/61350846-7ce09100-a89b-11e9-97e5-03ba388f59b4.png)

**Additional context**
Tried the following but bug persists:

- updated credentials - changing name, changing score, deleting name, etc.

- logged out and logged in

- uploaded documents (business legitimacy)

- edited financial data (vendor information)

- changing connection (Wi-Fi); internet connection is good

- switching between tabs

**Comment by Lex-Castro** [comment]
Upon further checking, this problem doesn't exist with the suppliers already in the system when UAT Cycle 2 started. 

This problem only persists on the new "suppliers that we invited" and has gone through the application process.

**Comment by zetaleona** [comment]
Remove the supplier in the status when declining accreditation.

![image](https://user-images.githubusercontent.com/50394125/62053588-80382d00-b24a-11e9-9aa0-94be27a8388a.png)
