### ISSUE TITLE
TS3: Company is not editable during account editing

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-pass-uat#48]
**Describe the bug**
Company field is not editable during editing of an account by the admin.

**To Reproduce**
1. Go to 'Manage Users'
2. Click on 'View', then 'Edit' for account to edit.
3. Enter data for Company field.

**Expected behavior**
Admin user should be able to edit the Company field. This field was editable during Cycle 1 testing.

**Screenshots**
![image](https://user-images.githubusercontent.com/51902789/61421926-db5d4c00-a93b-11e9-88a5-88506264b6ee.png)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Comment by paulinapaulinapaulina** [comment]
Sir Matt,

Please clarify why the field was disabled. Is this the possible data integrity issue?

**Comment by HannahCastro** [comment]
As of August 9, Company field is still not editable by Admin. Admin should be able to edit this field.
![image](https://user-images.githubusercontent.com/51902789/62751402-28919100-ba96-11e9-8871-24d796687a29.png)

**Comment by Lex-Castro** [comment]
I believe this is for closing. Company name can now be edited:

![image](https://user-images.githubusercontent.com/52643156/81555969-15f90f00-93bc-11ea-883e-90ac1422b69a.png)
