### ISSUE TITLE
UI: Overlapping Menu

### ISSUE THREAD

**Issue by Lex-Castro** [vasavah/vsv-fli-pass-uat#51]
**Describe the bug**
Notification Menu and Accreditor Notification Menu overlaps

**To Reproduce**
1. Click Notification button
2. Click other notification button
3. See error

**Expected behavior**
Notification buttons' visibility should be mutually exclusive. opening one menu should close the other

**Screenshots**
![image](https://user-images.githubusercontent.com/52643156/61442683-a7554b80-a97a-11e9-94bb-51a3a7a1fb80.png)

**Comment by HannahCastro** [comment]
This is now for closing.
