### ISSUE TITLE
TS26: Vendor is still able to use credentials after 8 hours

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-pass-uat#54]
**Describe the bug**
Email invite stated that the account credentials are only valid for 8 hours. Vendor was invited at around 6PM July 18, 2019 but was able to access the account at 8AM July 19, 2019 (more than 8 hours).

**To Reproduce**
1. Go to 'Invite New Supplier'
2. Enter details (supplier name: JBC contact name: JBC contact mobile number: 1234567 contact email address: iamjamaeca@gmail.com) and click on 'Invite New Supplier' once done.
3. Vendor doesn't access their account for at least 8 hours.
4. Access PASS website
5. Enter account credentials (username: jbc28 password:qwerty)
6. See error

**Expected behavior**
Vendor should not be able to access the account credentials after 8 hours. If they still wish to proceed with the invite, they will contact SAT so that the latter can resend the invite.

**Screenshots**
![image](https://user-images.githubusercontent.com/51902789/61501646-c0094400-aa02-11e9-97fe-3c8bcea53c4e.png)
![image](https://user-images.githubusercontent.com/51902789/61501664-db744f00-aa02-11e9-9fff-01f7f4f404af.png)
![image](https://user-images.githubusercontent.com/51902789/61501689-fcd53b00-aa02-11e9-8fef-7bb7b01c84d2.png)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Additional context**
In addition, the re-invitation will work once TS19: System allowed user to proceed inviting existing company is resolved. Lex has provided a new comment for this.
- If a vendor is just invited (didn't fill up the application form), SAT or canvassers should be able to still invite them.

**Comment by HannahCastro** [comment]
Please note that since the validity of the application doesn't expire, vendor is not tagged as "No Response". If an application has lapsed, vendor should be tagged as "No Response", and users should be able to reinvite them again.

**Comment by paulinapaulinapaulina** [comment]
The ticket is on hold pending completion of other prerequisite tickets.

**Comment by HannahCastro** [comment]
@paulinabernardo may we know the status of this ticket?

**Comment by HannahCastro** [comment]
This issue is resolved.
![image](https://user-images.githubusercontent.com/51902789/83702205-91a64e80-a63e-11ea-8462-ed72494c6fbe.png)
