### ISSUE TITLE
TS19: Email Invitation wrong website

### ISSUE THREAD

**Issue by Lex-Castro** [vasavah/vsv-fli-pass-uat#56]
**Describe the bug**
The email invitation for vendors reflect Filinvest Land, Inc. website (also other typos and suggestions in email invitation, see screenshots)

**Expected behavior**
The email invitation for vendors should show website of www.filinvestgroup.com

**Screenshots**
![image](https://user-images.githubusercontent.com/52643156/61505324-f3eb6600-aa10-11e9-858f-4eaf6a616be2.png)

make left align or justified alignment; "W" which stands for "website" is not in the same line with the website
![image](https://user-images.githubusercontent.com/52643156/61505353-167d7f00-aa11-11e9-8c43-69f3f386b8f7.png)

Add "Filinvest PASS" Logo to all emails
![image](https://user-images.githubusercontent.com/52643156/61505430-62c8bf00-aa11-11e9-852e-455319fc3e51.png)
![image](https://user-images.githubusercontent.com/52643156/61505624-0d40e200-aa12-11e9-8e00-b6a9202e6f32.png)

**Comment by HannahCastro** [comment]
Greetings should be "Hi __________," instead.

The semi-colons should be "." instead.
"Please follow the link below for proper accreditation. You will be asked to create an account and comply with the accreditation requirements. Should you have concerns and/or inquires, feel free to email us at"
