### ISSUE TITLE
TS26: Vendor can't access application contents after viewing profile

### ISSUE THREAD

**Issue by Lex-Castro** [vasavah/vsv-fli-pass-uat#57]
**Describe the bug**
The link sent so vendors through invitation directs them to the 'Supplier Invitation Application' (which is correct) however, if they leave the page (view their profile), clicking the 'Supplier Invitation Application' "button" doesn't do anything.

**To Reproduce**
1. As a vendor, Go to 'Supplier Invitation Application'
2. Click on your 'profile' (the circle image with your company's initials)
3. Click on 'Supplier Invitation Application' on the left menu

**Expected behavior**
Clicking the 'Supplier invitation Application' should direct user to the designated page/tab

**Screenshots**
No screenshot; nothing happens when you click 'Supplier Invitation Application'

**Comment by HannahCastro** [comment]
To expound, if a vendor decides to proceed with filling up the application form after viewing their profile, the system doesn't show the application form even if it is clicked. The vendor will have to log out and log in again just so they can fill up the application form.
