### ISSUE TITLE
UI: Terms & Conditions

### ISSUE THREAD

**Issue by Lex-Castro** [vasavah/vsv-fli-pass-uat#59]
**Describe the bug**
Inconsistent labeling. Statement reads: "I have read and agree to the **Terms and Condition**." but download button reads: "Download **Terms and Agreement**"

**To Reproduce**
1. As vendor, go to 'Invited Supplier Application'
2. Finish all steps until 'Finalization'
3. See error

**Expected behavior**
Use **Terms and Condition**

**Screenshots**
![image](https://user-images.githubusercontent.com/52643156/61512671-3e7adb80-aa2d-11e9-9a42-1fe891f9b008.png)

**Additional context**
May i also request to make this more apparent: Larger Font; bold, etc.

**Comment by HannahCastro** [comment]
![image](https://user-images.githubusercontent.com/51902789/63248657-6793c380-c29a-11e9-858c-33fd423790fd.png)

This is now for closing.
