### ISSUE TITLE
UI: Dashboard (wrong labels)

### ISSUE THREAD

**Issue by Lex-Castro** [vasavah/vsv-fli-pass-uat#62]
**Describe the bug**
Label/header in cards read "Supplier Name"

**Expected behavior**
Label/header in cards should read "Vendor Name"

**Screenshots**
![image](https://user-images.githubusercontent.com/52643156/61531218-c4f8e280-aa58-11e9-95fd-a70ec5d63bb4.png)

**Comment by HannahCastro** [comment]
Header has now been updated to "Vendor Name".
![image](https://user-images.githubusercontent.com/51902789/62934660-b56e7e80-bdf7-11e9-9811-2bf3a500df83.png)

**This ticket can now be closed.**
