### ISSUE TITLE
UI: Clickable title in cards in dashboard

### ISSUE THREAD

**Issue by Lex-Castro** [vasavah/vsv-fli-pass-uat#63]
Some title cards are clickable (mouse pointer changes from default to clicking pointer)
image below shows clickable title that "repositions" the page when clicked; other clickable title does nothing.
![image](https://user-images.githubusercontent.com/52643156/61531634-fde58700-aa59-11e9-91bc-02585e2d8711.png)

**Comment by paulinapaulinapaulina** [comment]
Title cards should not be clickable as dashboard are fixed.

**Comment by zetaleona** [comment]
Title cards are still clickable.

![Capture](https://user-images.githubusercontent.com/50394125/62053844-048ab000-b24b-11e9-9036-d4eb4923f8e5.PNG)
![Capture1](https://user-images.githubusercontent.com/50394125/62053852-06ed0a00-b24b-11e9-868d-021e9d8ced6a.PNG)

**Comment by HannahCastro** [comment]
> Title cards should not be clickable as dashboard are fixed.

Hi @Lex-Castro, please see comment of Paulina.
