### ISSUE TITLE
UI: "Company Name"

### ISSUE THREAD

**Issue by Lex-Castro** [vasavah/vsv-fli-pass-uat#67]
Would like to request changes in fields/labels related to "company name"

**When vendors are filling out:**
Change: Field: from "Company Name" to "BIR Registered Name" _(If local vendor only, international vendors will still have "Company Name"_
Add: Field: "Trade Name" _(if local vendor only, international vendors will not see this)_

Change: Field: "Classification" place this field before company name
![image](https://user-images.githubusercontent.com/52643156/61850546-2997bf80-aee7-11e9-9ab1-e032f6730cde.png)

**When inviting Vendors**
Change: Field: from "Company Name" to Trade Name 
![image](https://user-images.githubusercontent.com/52643156/61850840-d83c0000-aee7-11e9-878b-1e6d1c99097b.png)

**Comment by paulinapaulinapaulina** [comment]
Requirement 1

**If Local Vendor:**
Field name should be "BIR Registered Name"
Additional field: Trade Name 

**If international vendor:**
Field name should be "Company Name"
No additional field. Trade Name field should not be visible to international vendors.

Requirement 2

"Classification" field should be before Company Name/BIR Registered Name/Trade Name

Requirement 3

When inviting vendors use Trade Name NOT Company Name
