### ISSUE TITLE
Tag Inactive Vendors

### ISSUE THREAD

**Issue by zetaleona** [vasavah/vsv-fli-pass-uat#68]
Add a radio button to tag vendors as Active or Inactive.

**Comment by HannahCastro** [comment]
As of August 19, this has not been added yet.

**Comment by HannahCastro** [comment]
As of February 18, this issue is not yet resolved.

**Comment by Lex-Castro** [comment]
This has been resolved. For closing.

![image](https://user-images.githubusercontent.com/52643156/80932309-9aaec080-8df1-11ea-911b-f394ed934605.png)
![image](https://user-images.githubusercontent.com/52643156/80932312-a13d3800-8df1-11ea-827c-c9eb06ea5391.png)

**Comment by HannahCastro** [comment]
@zetaleona for your assistance in closing this ticket. Thanks!
