### ISSUE TITLE
Add Barangay Field

### ISSUE THREAD

**Issue by zetaleona** [vasavah/vsv-fli-pass-uat#69]
Create a new field for Barangay in Company/Vendor Info.

**Comment by HannahCastro** [comment]
As of August 19, this field has not been added yet.

**Comment by HannahCastro** [comment]
As of February 18, this issue is still not resolved.

**Comment by Lex-Castro** [comment]
This is now resolved.

**Comment by HannahCastro** [comment]
"Barangay" field has been added. @zetaleona kindly close this tickets. Thanks!
![image](https://user-images.githubusercontent.com/51902789/79937046-7a930f00-848b-11ea-85da-e757a1e45fd0.png)
