### ISSUE TITLE
TS34: Can't move forward/proceed with Invited Supplier Accreditation

### ISSUE THREAD

**Issue by Lex-Castro** [vasavah/vsv-fli-pass-uat#7]
**Describe the bug**
[as a vendor] Can't move forward with the process of accreditation due to the 'next' button being unclickable

**To Reproduce**
1. Go to 'Invited Supplier Application'
2. Accomplish all tabs until 'Government' tab
3. Click 'next'

**Expected behavior**
Process will move forward from 'Government' tab to 'Other Information'

**Screenshots**
![image](https://user-images.githubusercontent.com/52643156/60785816-ef0ff200-a186-11e9-8d90-f7d723e0052e.png)
![image](https://user-images.githubusercontent.com/52643156/60785841-fafbb400-a186-11e9-8215-d397fd5160b1.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Microsoft Edge]
 - Version [41.16299.15.0]

**Comment by Lex-Castro** [comment]
This seems to be an internet issue.

**Comment by HannahCastro** [comment]
This is for closing.
