### ISSUE TITLE
Add Zipcode Field

### ISSUE THREAD

**Issue by zetaleona** [vasavah/vsv-fli-pass-uat#70]
Create a new field for Zipcode in Company/Vendor Info.

**Comment by HannahCastro** [comment]
As of August 19, zip code has been added.
![image](https://user-images.githubusercontent.com/51902789/63233166-1b785d00-c261-11e9-91b7-17b2cfa677df.png)

**This ticket can now be closed.**

**Comment by HannahCastro** [comment]
@zetaleona Please close this ticket as this has been resolved.

**Comment by zetaleona** [comment]
> @zetaleona Please close this ticket as this has been resolved.

Noted.
