### ISSUE TITLE
Covert Trade to Tags from Free text

### ISSUE THREAD

**Issue by zetaleona** [vasavah/vsv-fli-pass-uat#71]
Convert Trade text field to tags field (similar to Github tags)

**Comment by HannahCastro** [comment]
As of August 19, this field is not yet included.

**Comment by HannahCastro** [comment]
As of February 18, this issue is not yet resolved.

**Comment by Lex-Castro** [comment]
This has been resolved. For closing.

**Comment by HannahCastro** [comment]
> This has been resolved. For closing.

Trade field is still free text field. As discussed during the walkthrough with CTI, this will be a multi-select field.
![image](https://user-images.githubusercontent.com/51902789/81388775-5c940280-914b-11ea-98d2-b750a2d0d6b0.png)

**Comment by HannahCastro** [comment]
@zetaleona for your closing.
![image](https://user-images.githubusercontent.com/51902789/83616771-d092c080-a5ba-11ea-95c8-9ec037d9b168.png)
