### ISSUE TITLE
TS1: System didn't prompt error for blank user role, department, designation 

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-pass-uat#72]
**Describe the bug**
Account isn't saved but system didn't prompt that user didn't fill up user role, department, and designation. User was able to click on Add User, then Proceed.

**To Reproduce**
1. Go to 'Manage Users'
2. Click on 'Add Users'
3. Fill-up all free text fields (first name, middle name, last name, contact number, email address, user name, and company)

**Expected behavior**
System should prompt as well that the drop down fields (user role, department, designation) weren't filled up as the value is still the default (Choose User Role/Department/Designation).

**Screenshots**
![image](https://user-images.githubusercontent.com/51902789/62750783-ecf5c780-ba93-11e9-8004-9d43a5af3f43.png)
![image](https://user-images.githubusercontent.com/51902789/62750788-ef582180-ba93-11e9-8507-0d188a466b8e.png)
![image](https://user-images.githubusercontent.com/51902789/62750791-f1ba7b80-ba93-11e9-8e4a-09c63e3669ac.png)
![image](https://user-images.githubusercontent.com/51902789/62750864-24647400-ba94-11e9-9032-6e088b70ee96.png)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Comment by Lex-Castro** [comment]
This is now working as expected, system does not allow user to proceed without choosing user role, department, designation and/or company.

![image](https://user-images.githubusercontent.com/52643156/81555267-e1d11e80-93ba-11ea-8298-92617957084b.png)
![image](https://user-images.githubusercontent.com/52643156/81555279-e564a580-93ba-11ea-8cb7-474d94b8038d.png)
![image](https://user-images.githubusercontent.com/52643156/81555292-eac1f000-93ba-11ea-8b00-7762f115ab80.png)
