### ISSUE TITLE
TS3: Not all changes in an account are noted in the activity/audit trail

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-pass-uat#73]
**Describe the bug**
Some changes in an account (whether changed by admin or the user) are not noted in the audit trail such as change in password or username. All activities/changes (account creation, account editing, account deactivation) should be noted so that it is easier to know what has been changed where and who changed it.
Also, activities noted are not specific (i.e. change info)

**To Reproduce**
1. Go to 'Manage Users' then 'View' to choose account (for admin)
2. Click on 'Edit', 'Change Password', 'Change Username', or 'Change Email Address'
3. Change data and click 'Save Changes'
4. See error (both using admin account and changed user's account)

**Expected behavior**
1. For activity/audit trail listing, all activities should be noted (i.e. account creation, account deactivation, account editing - change in password, change in email address, etc.).
2. For notes in the activity/audit trail listing, these should be more specific. This should include what has been changed, where and when it was changed, and who changed it. This should appear in the account of the user that changed the data (if admin changed) and the account that was changed.
ex.1 [date, time] rizza.ico created account of Dan Tiburcio.
ex.2 [date, time] hanna.castro changed Rizza Ico's password.
ex.3 [date, time] pocholo.castro change their profile picture.
ex.4 [date, time] arme.luzande deactivated account of hanna.castro.

**Screenshots**
_Generalized audit trail listing_
![image](https://user-images.githubusercontent.com/51902789/62762843-a9638380-babc-11e9-9ce1-126a8a6a9c0a.png)
_Change made in account - username and password_
![image](https://user-images.githubusercontent.com/51902789/62764195-e0876400-babf-11e9-92db-d52803988a0b.png)
![image](https://user-images.githubusercontent.com/51902789/62764124-b766d380-babf-11e9-8c7e-297b533e2b35.png)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Comment by Lex-Castro** [comment]
Changes within the system are now specified by the system. For closing.
