### ISSUE TITLE
TS2: Deactivated account is able to use account if not logged out

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-pass-uat#74]
**Describe the bug**
An account that was deactivated by admin was still able to use their account since that account didn't log out of the system. Audit trail was also not updated.

**To Reproduce**
1. Go to 'Manage Users' and search for the account to be deactivated (Note: Said user has not logged out of the system)
2. Click on 'Deactivate'
3. Using deactivated account, see error

**Expected behavior**
If a user account is deactivated, system should log out the account so that user will not be able to use it. Audit trail should be updated (what account was deactivated and by who).

**Screenshots**
_Admin account_
![image](https://user-images.githubusercontent.com/51902789/62765743-5e00a380-bac3-11e9-9d89-f6b86e247e8b.png)
_Deactivated account not logged out_
![image](https://user-images.githubusercontent.com/51902789/62765860-a1f3a880-bac3-11e9-9254-c8e048dc3fab.png)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Comment by Lex-Castro** [comment]
I have two open tabs, one incognito and one regular.
the regular tab has PASS logged in with an Admin User
the incognito tab has PASS logged in with my account

I disabled my account using the admin user and proceeded to invite a vendor, I was able to invite a vendor but my account was logged out automatically after. Upon checking with the admin user account, the vendor I invited was successfully invited as per the system records:

![image](https://user-images.githubusercontent.com/52643156/81530423-6e67e680-9393-11ea-9706-03c857ee4adc.png)

**Comment by HannahCastro** [comment]
We're okay with this. Issue will be closed.
![image](https://user-images.githubusercontent.com/51902789/83593152-93b0d480-a58e-11ea-9bde-800ce535d858.png)
![image](https://user-images.githubusercontent.com/51902789/83593179-ac20ef00-a58e-11ea-8b2a-8b09db3e19f6.png)
![image](https://user-images.githubusercontent.com/51902789/83593232-cb1f8100-a58e-11ea-8626-b19f59932268.png)
