### ISSUE TITLE
TS96: First few columns of table listing are not freezed

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-pass-uat#75]
**Describe the bug**
First few columns of table listings are not freezed so it is hard to known what data you are looking at.

**To Reproduce**
1. As admin, go to 'Manage Users' or if you are viewing vendor listing, go to 'Vendor List' and choose the vendor category to view (ex. Accredited vendors)
2. Scroll down to view the scroll bar and scroll right
3. See error

**Expected behavior**
_**This was included in the additional requirements provided from CPCAD and OTP.**_
![image](https://user-images.githubusercontent.com/51902789/62909627-e5922f00-bdaf-11e9-9352-f8213f346f2f.png)
First 2 or 3 columns should be freezed for ease of access in viewing data in the listings. Headers should also be freezed.

**Screenshots**
_Manage User module_
![image](https://user-images.githubusercontent.com/51902789/62909802-b4fec500-bdb0-11e9-9586-41739c056a20.png)
_Vendor List module_
![image](https://user-images.githubusercontent.com/51902789/62909918-1888f280-bdb1-11e9-9450-962970d454e1.png)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Comment by Lex-Castro** [comment]
Top row (Header) is now frozen. Columns remain scrollable. 

![image](https://user-images.githubusercontent.com/52643156/80934165-76ef7880-8df9-11ea-9375-6047455280d9.png)

**Comment by HannahCastro** [comment]
This is okay for vendor lists but not for user management.
![image](https://user-images.githubusercontent.com/51902789/81374411-c4d5ea80-9131-11ea-9ab3-8fb22115e5ac.png)
![image](https://user-images.githubusercontent.com/51902789/81374386-b5ef3800-9131-11ea-9018-5da73639e8a0.png)

**Comment by VCI-Jojo** [comment]
@HannahCastro Kindly clarify the concern, do you want it applied also to User Management column headers? Thank you.

**Comment by HannahCastro** [comment]
@VCI-Jojo If this is possible in V1.0, yes, so as to align with the rest of the system.

**Comment by VCI-Jojo** [comment]
> @VCI-Jojo If this is possible in V1.0, yes, so as to align with the rest of the system.

This will be included in V1.0

**Comment by HannahCastro** [comment]
This issue is now resolved.
![image](https://user-images.githubusercontent.com/51902789/83590388-3c0f6a80-a588-11ea-87c5-7af674359e7f.png)
