### ISSUE TITLE
TS95: Label in vendor list is cut-off

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-pass-uat#76]
**Describe the bug**
In the dashboard, when dropdown for vendor list is clicked, you will see all the categories but one label (Recommended for Accreditation) is cut-off. We tried zooming out and it is still cut-off

**To Reproduce**
1. Go to Dashboard
2. Click on dropdown error for 'Vendor List'
3. See error

**Expected behavior**
All words in the labels should be visible in the default viewing screen.

**Screenshots**
_75%_
![image](https://user-images.githubusercontent.com/51902789/62910204-31de6e80-bdb2-11e9-960f-81937a148caa.png)
_50%_
![image](https://user-images.githubusercontent.com/51902789/62910400-ea0c1700-bdb2-11e9-81d2-ec5c38e8f487.png)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Comment by Lex-Castro** [comment]
This has now been resolved. For closing.
![image](https://user-images.githubusercontent.com/52643156/80932975-583ab300-8df4-11ea-95b5-fa22af029da0.png)
