### ISSUE TITLE
TS96: Category "Blacklisted Vendors" only contains vendor names

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-pass-uat#78]
**Describe the bug**
When category "Blacklisted Vendors" is chosen, the listing only contains the vendor name.

**To Reproduce**
1. Go to 'Vendor List'
2. Click on 'Blacklisted Vendors'
3. See error

**Expected behavior**
Data shown for vendors under Blacklisted Vendors should be the same as those in other categories such as Accredited Vendors, Rejected Vendors, etc. This is so that SAT and admin will be able to see the details for checking purposes as well as accreditation purposes.

**Screenshots**
![image](https://user-images.githubusercontent.com/51902789/62920441-5c432280-bdd8-11e9-8701-7762a38e3bb4.png)
_Should be like this:_
![image](https://user-images.githubusercontent.com/51902789/62920955-d1632780-bdd9-11e9-94dc-b7aa6e9d6f44.png)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Comment by Lex-Castro** [comment]
I think this is now resolved. Please close if so:
![image](https://user-images.githubusercontent.com/52643156/79750544-bae77580-8343-11ea-8a11-c2739a66e656.png)
