### ISSUE TITLE
TS95: "Blacklisted Vendors" in dashboard contains validity period

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-pass-uat#79]
**Describe the bug**
The box for "Blacklisted Vendors" in the dashboard contains validity period.

**To Reproduce**
1. On the dashboard, scroll down to 'Blacklisted Vendors'
2. See error

**Expected behavior**
Blacklisting a vendor doesn't require validity; rejection does. This data shouldn't be shown for blacklisted vendors but for rejected vendors instead.

**Screenshots**
![image](https://user-images.githubusercontent.com/51902789/63074979-6c870900-bf62-11e9-94f3-330de0fdd2f9.png)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Additional context**
SAT only removes a vendor from the Blacklisted list manually as there is no validity period.

**Comment by Lex-Castro** [comment]
I think this is now resolved, for closing. Thanks.

![image](https://user-images.githubusercontent.com/52643156/79750789-20d3fd00-8344-11ea-96d3-699bba158e20.png)
