### ISSUE TITLE
TS45: CMAP assessment - cannot decline accreditation

### ISSUE THREAD

**Issue by Lex-Castro** [vasavah/vsv-fli-pass-uat#8]
**Describe the bug**
Radio button is working but choices are not saved - only default choice applies because there's no "confirm", "save", "next", or "proceed" button. Whatever choice you make, it goes back to the default choice once you change tabs

**To Reproduce**
1. Go to 'CMAP assessment of a supplier application
2. Click on 'Accreditation decline' radio button in 'credit score (CMAP List Checking'
3. Since no "confirm/save changes or update" button, change to any tab

**Expected behavior**
There should be a "confirm/save changes or update" button where choice is saved and will reflect in the accreditation process - if "proceed with accreditation", grading is as is; if otherwise, grading will be disregarded and supplier application is rejected

**Screenshots**
![image](https://user-images.githubusercontent.com/52643156/60788550-93963200-a18f-11e9-91b0-63f6557e062f.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Microsoft Edge]
 - Version [41.16299.15.0]

**Comment by HannahCastro** [comment]
This is for closing. New ticket has been opened regarding CMAP assessment issue. TS45: CMAP assessment won't proceed
