### ISSUE TITLE
TS95: Change in vendor status doesn't include "New" tagging

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-pass-uat#80]
**Describe the bug**
When the status of a vendor is changed, there is no "New" tag attached to it so if you try to look for it, it doesn't appear at the top of the list

**To Reproduce**
1. Go to vendor "AN Company" and click on 'View'
2. Scroll down and click on ''Reject this Vendor"
3. Go to vendor category "Rejected Vendor"

**Expected behavior**
If the status of a vendor is changed, it will be considered new for that category so it should be tagged as "New". Without this, the vendor appears at the bottom part of the list so it is hard to check if there is no notification for it.

**Screenshots**
![image](https://user-images.githubusercontent.com/51902789/63075771-6a727980-bf65-11e9-95ff-f75ac7e2e153.png)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Additional context**
For the screenshot provided, AN Company was initially under "Ongoing Assessment" with the tagging "New". We forwarded the application for accreditation and rejection. When we checked the "For Review and Approval" category, the vendor appeared at the last few pages of the listing.

**Comment by Lex-Castro** [comment]
This is now resolved. For closing.

**Comment by HannahCastro** [comment]
"New" tagging for change in vendor status is now available.
![image](https://user-images.githubusercontent.com/51902789/81389840-06c05a00-914d-11ea-84a4-404202f6fa72.png)
