### ISSUE TITLE
TS96: Status of invited vendors is "No Status for this Company"

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-pass-uat#82]
**Describe the bug**
When viewing an invited company under the "Vendors" category in the dashboard, the status appeared as "No Status for this Company".

**To Reproduce**
1. Go to 'Vendors'
2. Click on dropdown and choose 'Vendor Name'
3. Input invited vendor name in the free text field (ex. Waitress NY).

**Expected behavior**
Since these are invited vendors and they already fall under the "Invited Vendors" listing, the status should be "Invited Vendors".

**Screenshots**
![image](https://user-images.githubusercontent.com/51902789/63139819-399c4e00-c012-11e9-9b3c-c07b53701ccd.png)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Comment by Lex-Castro** [comment]
Invited Vendors are no longer part of the "vendors" dashboard, instead are shown in the "invited vendors dashboard"

![image](https://user-images.githubusercontent.com/52643156/81527717-93f1f180-938d-11ea-8712-1ef6d9f3ec94.png)

![image](https://user-images.githubusercontent.com/52643156/81527726-994f3c00-938d-11ea-8f0e-60475cedd834.png)

**Comment by HannahCastro** [comment]
> Invited Vendors are no longer part of the "vendors" dashboard, instead are shown in the "invited vendors dashboard"
> 
> ![image](https://user-images.githubusercontent.com/52643156/81527717-93f1f180-938d-11ea-8712-1ef6d9f3ec94.png)
> 
> ![image](https://user-images.githubusercontent.com/52643156/81527726-994f3c00-938d-11ea-8f0e-60475cedd834.png)

Said vendors shouldn't be removed from the Vendors List. Instead of status as "No Status for this Company", status should be "Invited Vendor" (if vendor still hasn't processed their application. Status should update if vendor has processed application or is already ongoing assessment.

**Comment by HannahCastro** [comment]
This issue is now resolved.
![image](https://user-images.githubusercontent.com/51902789/83590543-97415d00-a588-11ea-8675-a5d16d7ac682.png)
![image](https://user-images.githubusercontent.com/51902789/83590652-d1126380-a588-11ea-9b6c-9a274d34c752.png)
