### ISSUE TITLE
TS21: Multiple invitation to vendor changed the access role

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-pass-uat#83]
**Describe the bug**
A vendor was invited twice. Name of the vendor still appeared in "Invited Vendors" listing but when checked in "Manage Users", user role of the vendor became "Accreditor Reviewer". When account was opened, the interface was for the said user role.

**To Reproduce**
1. Go to 'Invite New Vendor'
2. Input the following details
    a. Company Name: Waitress NY
    b. Contact Name: Sara Bareilles
    c. Contact Mobile Number: 1234567
    d. Contact Email Address: waitress@testlang.com
3. Click on 'Invite New Vendor'
4. Repeat steps 1 to 3 
5. See error

**Expected behavior**
User role of the invited vendor should still be for vendors.

**Screenshots**
![image](https://user-images.githubusercontent.com/51902789/63140413-6ea9a000-c014-11e9-9194-337464db40e2.png)
![image](https://user-images.githubusercontent.com/51902789/63140458-900a8c00-c014-11e9-88cc-c2ae402da614.png)
![image](https://user-images.githubusercontent.com/51902789/63140806-b846ba80-c015-11e9-822b-25b12228a5b2.png)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Comment by Lex-Castro** [comment]
Cannot reproduce error.

The vendor can be invited, and the system recognizes it and asks confirmation if I want to invite the company again, but the system does not reflect its existence in any records.

![image](https://user-images.githubusercontent.com/52643156/81529113-bafdf280-9390-11ea-862c-f5c295962425.png)

**Comment by HannahCastro** [comment]
> Cannot reproduce error.
> 
> The vendor can be invited, and the system recognizes it and asks confirmation if I want to invite the company again, but the system does not reflect its existence in any records.
> 
> ![image](https://user-images.githubusercontent.com/52643156/81529113-bafdf280-9390-11ea-862c-f5c295962425.png)

Recreated scenario using the following details.
Trade Name: Vasavah Consultancy, Inc.
Contact Name: Jojo Batenga
Contact Mobile Number: 8888-8888
Contact Email Address 1: test001@email.xy
Contact Email Address 2: test002@email.xy
![image](https://user-images.githubusercontent.com/51902789/81545906-2c976a00-93ac-11ea-879e-f0696e0d91cb.png)
![image](https://user-images.githubusercontent.com/51902789/81545969-4638b180-93ac-11ea-88e6-3f3f73f76d87.png)
![image](https://user-images.githubusercontent.com/51902789/81546021-5a7cae80-93ac-11ea-926f-baa4579ac86f.png)
![image](https://user-images.githubusercontent.com/51902789/81546055-65cfda00-93ac-11ea-9e8f-ac2a1a2064c3.png)
![image](https://user-images.githubusercontent.com/51902789/81546106-74b68c80-93ac-11ea-9614-a626408df85d.png)

Access role of vendor is not changed. We will close this ticket.
