### ISSUE TITLE
TS23: Validity of rejection is not shown

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-pass-uat#85]
**Describe the bug**
Validity of rejection is not shown in the vendor listing (same as what is shown for "Blacklisted Vendors").

**To Reproduce**
1. On the Dashboard, scroll down to 'Rejected Vendors'. Else, go to 'Vendor List' then 'Rejected Vendors'.
2. See error

**Expected behavior**
Validity period for rejection should be shown so that it is easier for users to know if a rejected vendor can be reinvited or not (especially if not possible to do checking of validity period for re-inviting vendor).

**Screenshots**
![image](https://user-images.githubusercontent.com/51902789/63151656-9280dc00-c03c-11e9-80d7-8a18b32bd157.png)
![image](https://user-images.githubusercontent.com/51902789/63151777-d247c380-c03c-11e9-8a76-91d5f56f1f5e.png)
_Pattern from this_
![image](https://user-images.githubusercontent.com/51902789/63151626-8137cf80-c03c-11e9-9a0a-6572def54a9f.png)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Comment by Lex-Castro** [comment]
This is now resolved. For closing:

![image](https://user-images.githubusercontent.com/52643156/80932176-eca31680-8df0-11ea-824f-974c66f65991.png)
