### ISSUE TITLE
TS32: PCAB Rating field is missing in Vendor Information

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-pass-uat#89]
**Describe the bug**
PCAB Rating field is missing in Vendor Information.

**To Reproduce**
1. Go to 'Invited Vendor Information' then 'Company Information'
2. See error

**Expected behavior**
There should be a PCAB Rating field for Contractors as this is included in the search/filtering function required by CPCAD/OTP.

**Screenshots**
![image](https://user-images.githubusercontent.com/51902789/63233858-19b09880-c265-11e9-897a-a1592056fae1.png)

**Desktop (please complete the following information):**

**Additional context**
[Additional Requirements for PASS.docx](https://github.com/vasavah/vsv-fli-pass-uat/files/3513869/Additional.Requirements.for.PASS.docx)

**Comment by Lex-Castro** [comment]
This is now resolved. For closing.

![image](https://user-images.githubusercontent.com/52643156/80932088-553dc380-8df0-11ea-9e8e-e0e8d38469b4.png)
