### ISSUE TITLE
TS96: PCAB Rating is not included in the columns and search/filter criteria

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-pass-uat#90]
**Describe the bug**
There is no PCAB Rating in the vendor listing, for column and search/filter criteria

**To Reproduce**
1. Go to 'Vendor List' and choose any criteria (ex. Approved Vendor)
2. See error

**Expected behavior**
There should be a PCAB Rating column and search criteria as this is a requirement from CPCAD/OTP.

**Screenshots**
![image](https://user-images.githubusercontent.com/51902789/63234170-b7f12e00-c266-11e9-9be1-8cdea34772e0.png)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Additional context**
[Additional Requirements for PASS.docx](https://github.com/vasavah/vsv-fli-pass-uat/files/3513893/Additional.Requirements.for.PASS.docx)

**Comment by Lex-Castro** [comment]
This is now resolved. For closing:

![image](https://user-images.githubusercontent.com/52643156/79750242-31d03e80-8343-11ea-885e-5b13f3152ed0.png)
