### ISSUE TITLE
TS99: Default rating in Vendor Information Page is only 2 stars

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-pass-uat#95]
**Describe the bug**
Default rating in Vendor Information page is only 2 stars.

**To Reproduce**
1. Go to 'Vendor List' > vendor category (ex. For Review and Approval)
2. Click on 'View' for a chosen vendor (ex. Hannah Montana)
3. See error

**Expected behavior**
Default rating should be 3 stars as this is the median rating. This will be updated after the yearly evaluation and should then reflect the score.

**Screenshots**
![image](https://user-images.githubusercontent.com/51902789/63247443-a4aa8680-c297-11e9-8167-3aea6200e8eb.png)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Comment by Lex-Castro** [comment]
This is now resolved. Default rating is three (3) stars. For closing.

**Comment by HannahCastro** [comment]
Default rating is now 3 stars.
![image](https://user-images.githubusercontent.com/51902789/79936184-51717f00-8489-11ea-8d37-51828fc674a5.png)
