### ISSUE TITLE
TS40: Audit trail listing is generic

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-pass-uat#96]
**Describe the bug**
Audit trail listing for activities done on vendor applications is generic.

**To Reproduce**
1. Go to 'Vendor List' > choose vendor category (ex. For Review and Approval)
2. Click on 'View' for company to process (ex. KYUJi Company)
3. Edit a field or upload a new document. Proceed with processing.
4. Click 'Audit Trail' on tab where field was edited.
5. See error

**Expected behavior**
Audit trail listing for activities done should be more specific so that when checked, admin will be able to see what has been changed where and who changed them.
Ex.1. Johanna Marizze Castro edited Executive Contact Number for KYUJi Company.
Ex.2 Pocholo Alexis Castro changed/uploaded Audit Financial Statement for JBC Corporation. 
Ex.3 Pocholo Alexis Castro submitted JBC Corporation for approval.
Ex.4 Sarah Jane Taleon accredited JBC Corporation.

**Screenshots**
![image](https://user-images.githubusercontent.com/51902789/63252315-31f2d880-c2a2-11e9-87c2-e25a8e59693a.png)
![image](https://user-images.githubusercontent.com/51902789/63253007-97939480-c2a3-11e9-86ed-beb23c97f586.png)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Comment by Lex-Castro** [comment]
This is now resolved. For closing.
'
![image](https://user-images.githubusercontent.com/52643156/80933634-237c2b00-8df7-11ea-815f-6e3e87c07a9a.png)

**Comment by HannahCastro** [comment]
Audit trail is not generic anymore.
![image](https://user-images.githubusercontent.com/51902789/81374929-f307fa00-9132-11ea-8a07-d927b51731ff.png)
