### ISSUE TITLE
TS45: CMAP feature to prevent skipping of assessment is malfunctioning

### ISSUE THREAD

**Issue by Lex-Castro** [vasavah/vsv-fli-pass-uat#97]
**Describe the bug**
There is a feature to prevent the user from accessing CMAP List Checking **if he/she has not done the other assessment for the vendor beforehand**.  However, there are times that this features is on or off (or sometimes it blinks in and out) regardless of the condition

![image](https://user-images.githubusercontent.com/52643156/63326748-77c1a680-c35f-11e9-8e06-1b833c6ec2c8.png)

**Comment by Lex-Castro** [comment]
As of 10 FEB 2020, this issue hasn't been resolved.

In the CMAP section, the section is buggy, it "flickers" between 'allowing users to CMAP check' and not allowing.

**Comment by Lex-Castro** [comment]
As of 20 APR 2020, this issue hasn't been resolved,

Expected Behavior:
In the CMAP section, the user (reviewer) must not have access in the function of the section if he/she has not done the assessment of the supplier beforehand.

_previous error is that the "blocking message" only flickers on and off, and sometimes is completely disabled and the user may freely access the CMAP section_

Actual Behavior:
If assessment has not yet been done, the "blocking message" only shows for a very brief moment and the actual section (the function) reveals itself shortly

I can't take a screenshot of the message because it only shows for a split second, however the image below shows the CMAP Section even though the supplier has not been assessed by the user.

![image](https://user-images.githubusercontent.com/52643156/79749098-2aa83100-8341-11ea-8e61-d2b72a882237.png)

**Comment by HannahCastro** [comment]
This issue is resolved. @zetaleona please assist in closing ticket.
![image](https://user-images.githubusercontent.com/51902789/83602167-9e766400-a5a4-11ea-8f1b-2e625d609d29.png)
