### ISSUE TITLE
TS40: Upload button for "Company ID (For Employee)" is not working

### ISSUE THREAD

**Issue by HannahCastro** [vasavah/vsv-fli-pass-uat#98]
**Describe the bug**
Button "Company ID (For Employee)" in vendor application form is clickable. But when you try to upload a file, system didn't save the file.

**To Reproduce**
1. Go to 'Vendor List' > vendor category (ex. For Review and Approval) > 'View' on vendor to process (ex. Pandora Handicraft)
2. Click on 'Choose Files' under 'Company ID (For Employee)' to upload document.
3. See error

**Expected behavior**
If file is uploaded successfully, file name should appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/51902789/63329685-fec54d80-c364-11e9-940f-164b9122e8ab.png)

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Google Chrome]
 - Version [75.0.3770.100]

**Comment by Lex-Castro** [comment]
All uploading functions of PASS when vendor is uploading is working. This is resolved.

**Comment by HannahCastro** [comment]
User is now able to upload a file for the "Company ID (For Employee)" field.
![image](https://user-images.githubusercontent.com/51902789/79935266-0f473e00-8487-11ea-8230-33809085463d.png)
