### ISSUE TITLE
TS47: Notification of Approver

### ISSUE THREAD

**Issue by Lex-Castro** [vasavah/vsv-fli-pass-uat#99]
The SAT Reviewer has two "notification" buttons, the "new" and the "bell" icon.
the new icon notifies SAT reviewer  the number of vendors (under ongoing assessment) that haven't been checked/verified yet.

The SAT Approver's new icon should notify him/her the number of vendors (under for review and approval) that haven't been accredited/ac

![image](https://user-images.githubusercontent.com/52643156/63336722-31c20e00-c372-11e9-8a39-987247774245.png)

**Comment by Lex-Castro** [comment]
The bell icon shows notifications when accounts have been updated (new accounts, updated accounts), but navigating through the accounts doesn't reduce the new notifications indicated by the red circle with no.
![image](https://user-images.githubusercontent.com/52643156/79712197-d1b6a980-82fc-11ea-844e-ab76d704f20e.png)

The new icon doesn't show anything yet, I'll check.

**Comment by HannahCastro** [comment]
Approver is not notified of applications that has been forwarded to them for rejection or approval.

**Comment by HannahCastro** [comment]
This issue is resolved. @zetaleona please assist in closing ticket.
![image](https://user-images.githubusercontent.com/51902789/83622208-3cc4f280-a5c2-11ea-9dec-8f69c3db7dca.png)
